### ISSUE TITLE
got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by kil98q** [jtydhr88/sd-webui-txt-img-to-3d-model#1]
![image](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/20018871/aea38ead-b23a-43f2-b21c-37740d27849b)

Cant seem to get it to work reinstalled the wholestable diffusion web ui to try an get it to run but no dice. Got any idea's?

**Comment by stephanschielke** [comment]
I believe that's the full error log (getting the same):
```
Traceback (most recent call last):
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
```

Probably something in the `gradio` package changed.

```
pip freeze | grep gradio
gradio==3.32.0
gradio_client==0.2.6
```

**Comment by jtydhr88** [comment]
@stephanschielke may I ask what version of your sd-webui?

**Comment by stephanschielke** [comment]
I think this refactoring is at fault:
https://github.com/gradio-app/gradio/compare/v3.31.0...v3.32.0#diff-5618d1266a84e86489b0312f75d11352cd7c0fa40fd0b39be64899426276615cR78

I found a dirty hotfix where you downgrade `gradio` from `3.32.0` to `3.31.0` and it works again:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements_versions.txt#L6

@jtydhr88 I'm running off the latest master which is tagged with `v1.3.2`

**Comment by jtydhr88** [comment]
Thanks @stephanschielke , I will research why this extension cause this (looks like) irrelevant issue this weekend

**Comment by jtydhr88** [comment]
hey guys, I made a fix for this issue, please let me know it still exists or now, close for now, just feel free to reopen it if still face it.

**Comment by stephanschielke** [comment]
Thanks a lot, @jtydhr88.

I can confirm the fix is working with the latest version.

**Comment by jmonostereo** [comment]
Getting the same error.

Traceback (most recent call last):
  File "/Users/juanmonasterio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/juanmonasterio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/juanmonasterio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/juanmonasterio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/Users/juanmonasterio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by Hrdhad123** [comment]
Hello i am getting this error

Traceback (most recent call last):
  File "C:\Users\harsh\OneDrive\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\harsh\OneDrive\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\harsh\OneDrive\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\harsh\OneDrive\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "C:\Users\harsh\OneDrive\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

can u help me out

**Comment by jtydhr88** [comment]
@Hrdhad123 please check out my previous comment and refer to https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/issues/3

**Comment by AACodek** [comment]
completed removed venv.
redownloaded and got the same error :(

Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(

  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)

  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))

  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)

  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(

TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by TerryJia** [comment]
@AACodek thanks for reporting this issue, I will take a look at it soon

**Comment by jtydhr88** [comment]
@AACodek thanks for reporting this issue, I will take a look at it soon
