### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Anyeos** [jtydhr88/sd-webui-txt-img-to-3d-model#19]
```
mode:txt
clip_denoised:True
use_fp16:True
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "venv/lib/python3.8/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "venv/lib/python3.8/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "venv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "extensions/sd-webui-txt-img-to-3d-model/scripts/main.py", line 52, in generate
    xm = load_model('transmitter', device=device)
  File "extensions/sd-webui-txt-img-to-3d-model/shap_e/models/download.py", line 144, in load_model
    from .configs import model_from_config
  File "extensions/sd-webui-txt-img-to-3d-model/shap_e/models/configs.py", line 20, in <module>
    from shap_e.models.nerstf.mlp import MLPDensitySDFModel, MLPNeRSTFModel
  File "extensions/sd-webui-txt-img-to-3d-model/shap_e/models/nerstf/mlp.py", line 7, in <module>
    from shap_e.models.stf.mlp import MLPModel
  File "extensions/sd-webui-txt-img-to-3d-model/shap_e/models/stf/mlp.py", line 14, in <module>
    from .base import Model
  File "extensions/sd-webui-txt-img-to-3d-model/shap_e/models/stf/base.py", line 11, in <module>
    class Model(ABC):
  File "extensions/sd-webui-txt-img-to-3d-model/shap_e/models/stf/base.py", line 18, in Model
    ) -> AttrDict[str, Any]:
TypeError: 'type' object is not subscriptable

```

**Comment by jtydhr88** [comment]
Hi @Anyeos , a general suggestion is to use Python 3.10 and rebuild SD-webui env, I can see you are using with python 3.8 which isn’t my env.

**Comment by Anyeos** [comment]
Ok, thanks for your answer but I am using Ubuntu 20.04 and there are no official Python 3.10 but I have conda installed specifically for AI with a Python 3.10 I will try if I can call webui from a conda activated environment.

**Comment by Anyeos** [comment]
Ok, I got it work. On Ubuntu 20.04 using conda (installed manually, conda not miniconda) I have an env with Python 3.10. At the same time running webui what creates an venv (previous activate with conda) it installs the rest and after some fine-tuning (some version conflict or wrong auto installed) it is working. It don't took too much time.

So if there are more people in same situation (no Python 3.10) they can use conda.

**Comment by jtydhr88** [comment]
Thanks @Anyeos headsup, I would like to close this issue for now since we already got the solution
