### ISSUE TITLE
Doesn't work (different reason)

### ISSUE THREAD

**Issue by Ainaemaet** [jtydhr88/sd-webui-txt-img-to-3d-model#3]
Hello. Installed using the extensions installer inside Automatic1111 on a freshly updated and confirmed working install. 

Got the following error after putting in a prompt and forgetting I was on IMG, then I watched it download the model and then gave an error (can't remember the error as I restarted my WSL2 instance). 
Then, after changing over to TXT and putting in a prompt, I see no attempts at downloading anything and get this: 

mode:txt
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/automatic/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/username/anaconda3/envs/automatic/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/username/anaconda3/envs/automatic/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/username/anaconda3/envs/automatic/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/username/anaconda3/envs/automatic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/username/anaconda3/envs/automatic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/username/machinelearning/mediacreation/sd-webui/extensions/sd-webui-txt-img-to-3d-model/scripts/main.py", line 51, in generate
    model = load_model(model_name, device=device)
  File "/home/username/machinelearning/mediacreation/sd-webui/extensions/sd-webui-txt-img-to-3d-model/shap_e/models/download.py", line 146, in load_model
    model = model_from_config(load_config(model_name, **kwargs), device=device)
  File "/home/username/machinelearning/mediacreation/sd-webui/extensions/sd-webui-txt-img-to-3d-model/shap_e/models/configs.py", line 133, in model_from_config
    inner_model = model_from_config(inner_config, device)
  File "/home/username/machinelearning/mediacreation/sd-webui/extensions/sd-webui-txt-img-to-3d-model/shap_e/models/configs.py", line 117, in model_from_config
    return CLIPImagePointDiffusionTransformer(device=device, dtype=torch.float32, **config)
  File "/home/username/machinelearning/mediacreation/sd-webui/extensions/sd-webui-txt-img-to-3d-model/shap_e/models/generation/transformer.py", line 256, in __init__
    self.clip = (FrozenImageCLIP if frozen_clip else ImageCLIP)(device)
  File "/home/username/machinelearning/mediacreation/sd-webui/extensions/sd-webui-txt-img-to-3d-model/shap_e/models/generation/pretrained_clip.py", line 221, in __init__
    self.model = ImageCLIP(device, dtype=None, ensure_used_params=False, **kwargs)
  File "/home/username/machinelearning/mediacreation/sd-webui/extensions/sd-webui-txt-img-to-3d-model/shap_e/models/generation/pretrained_clip.py", line 37, in __init__
    self.clip_model, self.preprocess = clip.load(
AttributeError: module 'clip' has no attribute 'load'

**Comment by jtydhr88** [comment]
Hey, may I ask the information of sd webui? Like version?

**Comment by jtydhr88** [comment]
But from the error log, looks like you have a incompatible version of dependency, clip.
And the general suggestion is: first, update your webui to latest, I guess it is 1.3.2, then remove or rename your webui/venv folder to something else to backup your current environment, then rerun your webui, you will get the latest version of your webui

**Comment by Ainaemaet** [comment]
Ok, will try that and get back - thank you for the quick response. 
Indeed I've been doing so much lately between env's I thought this was fresh but this was after an update on an old version.

**Comment by Ainaemaet** [comment]
That did it, all is working fine now. Great work (can't wait to see where this is going), and thanks again.
